src/pages/MdViewerPage/ContentTable.tsx, src/pages/MdViewerPage/MdViewerPage.tsx, src/pages/MdViewerPage/headingStyle.css
This is for fix some wrong margin and style of the md-page
=> correct margin and other style md page

public/index.html
this pr , is for fix that icon don't show in safari browser
=> Fix/fix favicon don't show safari

src/components/cards/CollateralsCard.tsx, src/components/cards/JustifiedRowItem.tsx
This is for fix the style in card collaterals
https://trello.com/c/d9XI1Ukn/65-make-changes-to-the-collateral-cards
=> add style to collaterals cards

src/collateral-structure.yaml
This is for display specific parameters in the first place
https://trello.com/c/QsW5zSBP/58-display-specific-parameters-in-the-first-place
=> add specific parameters

yarn.lock
=> Prod Feb 24 2:00pm

src/components/inputs/DatePicker.tsx, src/pages/SpellPage/SpellsContainerPage.tsx
https://trello.com/c/GTHYeh3r/90-fix-filtering-by-date-in-the-spells-view
=> including start and end date in the selection

src/components/bars/NavBar.tsx, src/components/inputs/DatePicker.tsx, src/components/lists/SpellList/ExpandableRowsComponent.tsx, src/components/lists/SpellList/SpellList.tsx, src/components/lists/SpellList/cells.tsx, src/components/lists/SpellList/spellColumns.tsx, src/pages/SpellPage/SpellsContainerPage.tsx, src/pages/SpellPage/SpellsPage.tsx, src/services/loadData/spells/useLoadSpells.ts
https://trello.com/c/AUDinl6L/97-improvements-in-the-spells-view
https://trello.com/c/ZLJ0YNEy/78-fix-filter-by-spells-parameters
=> fix improvements in the spells view

src/context/MainContext.tsx
ticket
https://trello.com/c/6mavuKv3/91-review-the-collaterals-view-in-safari-browser
=> fix issue of load collaterals in old version of safari

src/collateral-structure.yaml, src/components/lists/CollateralList/mappingCollateralsData.ts, src/services/loadData/useLoadCollaterals.ts, src/services/loadData/useLoadDirectContract.ts, src/services/utils/currencyResource.ts, src/types.d.ts
https://trello.com/c/AbdUKMSb/95-change-the-parameter-in-the-direct-deposit-collateral-types
=> adding bar parameter in direct deposit

src/context/MainContext.tsx
Ticket
https://trello.com/c/PJLCTNGe/87-review-the-stats-values-in-the-dashboard
=> fix collaterals in the main context

src/components/lists/SpellList/SpellList.tsx, src/pages/SpellPage/SpellsContainerPage.tsx
https://trello.com/c/ZLJ0YNEy/78-fix-filter-by-spells-parameters
=> expanded the first spell by default

src/components/charts/StackBarChart/Summary.tsx
The component code has been modified to make it more reusable and make it easier to place or remove component parameters.
Card: [Hide Two Parameters from the Bar Graph](https://trello.com/c/AQdvkqXc/132-hide-two-parameters-from-the-bar-graph)
=> refactor: hide two parameters from the bar graph

src/components/lists/CollateralSpellList/collateralSpellsColumns.tsx
* The Source Type column was added
[Unhide 'Source Type' in the Spells Parameters (Changelogs) Page](https://trello.com/c/LL8W0wSj/133-unhide-source-type-in-the-spells-parameters-changelogs-page)
=> feat: add Source Type column

src/components/lists/CollateralSpellList/collateralSpellsColumns.tsx, src/types.d.ts
* Fix the source type parameter
[Unhide 'Source Type' in the Spells Parameters (Changelogs) Page](https://trello.com/c/LL8W0wSj/133-unhide-source-type-in-the-spells-parameters-changelogs-page)
=> fix: source type parameter

src/components/lists/CollateralSpellList/collateralSpellsColumns.tsx, src/services/utils/transformSpellChanges.ts
=> fix: change value formatting in the parameters table

src/components/charts/PieChart/LegendItems.tsx, src/components/charts/PieChart/PieChart.tsx, src/components/charts/PieChart/PieChartContainer.tsx, src/components/charts/StackBarChart/StackBarChart.tsx, src/components/styledComponents/Label.tsx, src/components/styles/ThemeProvider.tsx, src/pages/OverviewPage/OverviewPage.tsx
[Improve the Design for 1366x768 Breakpoint](https://trello.com/c/sINRLceU/144-improve-the-design-for-1366x768-breakpoint)
=> feat/style: improve the design for 1366x768 breakpoint

src/components/charts/PieChart/PieChartContainer.tsx
[Improve the Design for 1366x768 Breakpoint](https://trello.com/c/sINRLceU/144-improve-the-design-for-1366x768-breakpoint)
=> style: change the font size in PieChart to 1535px

src/components/lists/CollateralSpellList/collateralSpellsColumns.tsx, src/params-labels.yaml, src/services/utils/FormatterSpells.ts, src/services/utils/transformSpellChanges.ts
=> fix: parameters format

src/services/utils/transformSpellChanges.ts
=> fix: Liquidation Penalty values

src/components/charts/PieChart/PieChart.tsx, src/services/formatters/CollateralsDataFormat.ts
=> fix: add 2 decimal places to pie chart parameters and collaterals

src/components/lists/SpellList/changeColumns.tsx
=> style: change 'There Is No Collateral Related' message to capitalize

src/collateral-structure.yaml, src/components/charts/PieChart/LegendItems.tsx, src/components/charts/PieChart/PieChart.tsx, src/components/charts/PieChart/PieChartContainer.tsx
[Add Links to the Doc for the Parameters in the Pie Chart](https://trello.com/c/6HTB2FMU/151-add-links-to-the-doc-for-the-parameters-in-the-pie-chart)
[Merge GUNIV3DAIUSDC in the Pie Chart](https://trello.com/c/kTdiPOPz/150-merge-guniv3daiusdc-in-the-pie-chart)
=> New Pie Chart features

src/components/charts/PieChart/PieChart.tsx, src/components/charts/PieChart/PieChartContainer.tsx
[Merge GUNIV3DAIUSDC in the Pie Chart](https://trello.com/c/kTdiPOPz/150-merge-guniv3daiusdc-in-the-pie-chart)
=> fix: The Stability fee does not have a correct value on the pie Chart

src/components/charts/StackBarChart/Summary.tsx
[Change a Link to the Doc for the Ceiling Parameter in the Bar Chart](https://trello.com/c/tYcVjI63/152-change-a-link-to-the-doc-for-the-ceiling-parameter-in-the-bar-chart)
=> fix: Change a Link to the Doc for the Ceiling Parameter in the Bar Chart

src/components/charts/PieChart/PieChart.tsx, src/services/formatters/CollateralsDataFormat.ts, src/services/formatters/FormattingFunctions.ts, src/services/formatters/ParameterFormattingSwitch.ts
Rectify the function for formatting values to percent
=> fix: percent function

src/components/charts/PieChart/PieChart.tsx, src/components/charts/StackBarChart/StackBarChartContainer.tsx, src/components/charts/StackBarChart/Summary.tsx, src/services/formatters/FormattingFunctions.ts
[Improvements](https://trello.com/c/3LonEezH/156-improvements)
=> fix: change the name of the Ceiling parameter to Debt Ceiling

src/collateral-structure.yaml, src/services/formatters/ParameterFormattingSwitch.ts
[Add to Target Borrow Rate parameter doc link and % unit.](https://trello.com/c/Eu3RXUqH/160-add-to-target-borrow-rate-parameter-doc-link-and-unit)
=> fix: add to Target Borrow Rate parameter doc link and % unit
